export const highPriorityWords = [
  "Work",
  "Urgent Tasks",
  "Meetings",
  "Client Projects",
  "Deadlines",
  "Team Collaboration",
  "Critical Updates",
  "Important Announcements",
  "Business Opportunities",
  "Leadership",
  "Strategy",
  "Client Support",
  "Emergency",
  "Action Required",
  "Job Application",
  "Legal",
  "Finance",
  "Management",
  "Product Launch",
  "HR Issues",
  "Sales",
  "Customer Complaints",
  "Investments",
  "Company Policies",
  "Performance Reviews",
  "Negotiations",
  "Risk Management",
  "Cybersecurity",
  "Compliance",
  "Crisis Management",
  "Budgeting",
  "Marketing Campaigns",
  "Resource Planning",
  "Training",
  "Product Development",
  "Customer Service",
  "Productivity",
  "Press Releases",
  "New Contracts",
  "Business Travel",
  "Partnerships",
  "Mergers and Acquisitions",
  "International Projects",
  "Time-Sensitive",
  "Pressing Matters",
  "Executive Decisions",
  "Team Performance",
  "Financial Reporting",
  "Employee Wellbeing",
  "Workplace Safety",
  "Networking",
  "Regulatory Issues",
  "Project Milestones",
  "Internal Memo",
  "Product Feedback",
  "Team Building",
  "Quality Assurance",
  "Budget Approval",
  "Business Continuity",
  "Customer Retention",
  "Recruitment",
  "Product Updates",
  "Marketing Strategy",
  "Investor Relations",
  "Consulting",
  "Franchise Operations",
  "Operational Efficiency",
  "Supply Chain",
  "Market Research",
  "Customer Experience",
  "IT Infrastructure",
  "Corporate Events",
  "Talent Acquisition",
  "Board Meetings",
  "Investor Updates",
  "Public Relations",
  "Customer Engagement",
  "Brand Reputation",
  "Industry Trends",
  "Risk Assessment",
  "Employee Training",
  "Corporate Social Responsibility",
  "Legal Compliance",
];

export const lowPriorityWords = [
  "Promotions",
  "Social",
  "Spam",
  "Newsletters",
  "Advertisements",
  "Discounts",
  "Retail Offers",
  "Product Deals",
  "Birthday Offers",
  "Gift Cards",
  "Coupons",
  "Surveys",
  "Events",
  "Publicity",
  "Celebrity News",
  "Travel Deals",
  "Special Offers",
  "Contests",
  "New Arrivals",
  "Trending Topics",
  "TV Shows",
  "Movies",
  "Music Releases",
  "Entertainment News",
  "Celebrity Gossip",
  "Fashion Trends",
  "Celebrity Endorsements",
  "Fitness",
  "Health Tips",
  "Recipe Ideas",
  "Sports News",
  "Fan Updates",
  "Social Media Notifications",
  "Celebrity Interviews",
  "Book Recommendations",
  "Restaurant Promotions",
  "Concerts",
  "Hobbies",
  "Gift Suggestions",
  "Product Reviews",
  "User Testimonials",
  "DIY Projects",
  "Seasonal Trends",
  "Brand Announcements",
  "Product Testing",
  "Crowdfunding",
  "Customer Reviews",
  "Tech News",
  "Shopping Cart Reminders",
  "Local Offers",
  "Travel Blogs",
  "Tourist Destinations",
  "Volunteer Opportunities",
  "Online Learning",
  "Self-Improvement",
  "Weekly Deals",
  "Online Surveys",
  "Job Alerts",
  "Content Creators",
  "Influencer Marketing",
  "Viral Content",
  "E-commerce News",
  "Home Decor",
  "Style Tips",
  "Shopping Guides",
  "Personal Finance Tips",
  "Life Hacks",
  "Tech Gadgets",
  "Smartphone Releases",
  "Photography",
  "Art Exhibitions",
  "Graphic Design",
  "3D Printing",
  "Crowdsourcing",
  "Interior Design",
  "Home Improvement",
  "Gifting Ideas",
  "Social Events",
  "Non-profit Campaigns",
  "Public Service Announcements",
  "Mental Health Resources",
  "Sustainability Tips",
  "Charity Drives",
  "Environment",
  "Recycling Tips",
  "Gardening",
  "Pet Care",
  "Family Activities",
  "Back-to-School Promotions",
  "Parenting",
  "Fashion Sales",
  "Camping and Outdoors",
  "Winter Gear",
  "Eco-friendly Products",
  "Health and Wellness",
  "New Store Openings",
  "Tech Tutorials",
  "Fashion Advice",
  "Beauty Tips",
  "Fitness Challenges",
  "Volunteer News",
  "Pet Adoption",
  "Local Markets",
  "Auction Alerts",
  "Fundraising Events",
  "Pop Culture",
  "Crafts",
  "Art Projects",
  "Creative Writing",
  "Poetry",
  "Yoga and Meditation",
  "Mindfulness",
  "Work-Life Balance",
  "Photography Competitions",
];

export const highPriorityKeywords = [
  "urgent",
  "action required",
  "asap",
  "important",
  "follow-up",
  "immediate attention",
  "response needed",
  "priority",
  "critical",
  "high importance",
  "time-sensitive",
  "attention required",
  "mandatory",
  "essential",
  "deadline approaching",
  "final notice",
  "don't delay",
  "top priority",
  "needs approval",
  "response requested",
  "high priority",
  "immediate action",
  "review needed",
  "quick update",
  "fast response",
  "please confirm",
  "verification required",
  "pending approval",
  "urgent reply",
  "due soon",
  "important update",
  "review immediately",
  "action needed now",
  "decision required",
  "attention needed",
  "read asap",
  "important details",
  "please respond",
  "quick turnaround",
  "high urgency",
  "critical update",
  "follow-up required",
  "update needed",
  "immediate follow-up",
  "prompt attention",
  "priority update",
  "status update required",
  "final reminder",
  "immediate deadline",
  "high impact",
  "response required now",
  "urgent matter",
  "please advise",
  "time-critical",
  "reply requested",
  "mandatory action",
  "need clarification",
  "pending response",
  "next steps required",
  "request for approval",
  "pressing issue",
  "needs resolution",
  "address immediately",
  "please act",
  "urgent task",
  "please handle",
  "feedback needed",
  "requires action",
  "review required",
  "critical matter",
  "priority task",
  "review requested",
  "prompt response",
  "feedback required",
  "time-sensitive matter",
  "please review",
  "requires approval",
  "confirm immediately",
  "follow-up asap",
  "for your attention",
  "quick resolution",
  "resolve urgently",
  "escalated issue",
  "decision needed now",
  "next steps asap",
  "critical decision",
  "update required asap",
  "time-sensitive action",
  "urgent follow-up",
  "immediate review",
  "priority matter",
  "read immediately",
  "address urgently",
  "important follow-up",
  "confirm required",
  "please resolve",
  "urgent update required",
  "decision required urgently",
  "critical resolution",
  "urgent confirmation",
  "final decision needed",
  "urgent clarification",
  "please prioritize",
];

export const emailKeywords = {
  important: [
    "urgent",
    "important",
    "asap",
    "critical",
    "action required",
    "immediate attention",
    "deadline",
    "priority",
    "follow-up",
    "response needed",
    "high priority",
    "please respond",
    "do not ignore",
    "escalate",
    "mandatory",
    "alert",
    "final notice",
    "pending",
    "take action",
    "to be done",
  ],
  workUpdates: [
    "project",
    "update",
    "team",
    "meeting",
    "work",
    "status",
    "report",
    "deadline",
    "task",
    "assignment",
    "collaboration",
    "agenda",
    "minutes",
    "deliverable",
    "milestone",
    "follow-up",
    "progress",
    "planning",
    "strategy",
    "action items",
  ],
  promotionalEmails: [
    "offer",
    "discount",
    "sale",
    "deal",
    "exclusive",
    "limited time",
    "promotion",
    "buy now",
    "free",
    "save",
    "new arrival",
    "gift",
    "voucher",
    "coupon",
    "special price",
    "reward",
    "bundle",
    "clearance",
    "shop now",
    "last chance",
  ],
  paymentsAndInvoices: [
    "invoice",
    "payment",
    "receipt",
    "bill",
    "transaction",
    "due",
    "paid",
    "refund",
    "tax",
    "charges",
    "balance",
    "overdue",
    "credit",
    "debit",
    "fee",
    "transfer",
    "statement",
    "deposit",
    "withdrawal",
    "pay now",
    "outstanding",
    "txn",
    "billing",
    "payment confirmation",
    "PhonePe",
    "Paytm",
    "Google Pay",
    "UPI",
    "NEFT",
    "RTGS",
    "IMPS",
    "wallet",
    "credit card",
    "debit card",
    "bank",
    "payment received",
  ],
  socials: [
    "social",
    "friend",
    "community",
    "connection",
    "notification",
    "invite",
    "followers",
    "likes",
    "comment",
    "mention",
    "share",
    "event",
    "network",
    "group",
    "profile",
    "recommendation",
    "message",
    "chat",
    "tagged",
    "conversation",
    "facebook",
    "instagram",
    "twitter",
    "linkedin",
    "snapchat",
    "tiktok",
    "pinterest",
    "reddit",
    "youtube",
    "whatsapp",
    "telegram",
    "discord",
    "twitch",
    "vimeo",
    "tumblr",
    "wechat",
    "kakaotalk",
    "line",
    "qq",
    "signal",
    "clubhouse",
    "slack",
    "beReal",
    "mastodon",
    "parler",
    "truth social",
    "substack",
    "medium",
    "flickr",
    "mix",
    "dribbble",
    "behance",
    "goodreads",
    "patreon",
    "onlyfans",
    "nextdoor",
    "quora",
    "vine", // legacy but still relevant in some contexts
    "x", // formerly Twitter
    "wechat moments",
    "vk",
    "odnoklassniki",
    "renren",
    "badoo",
    "meetup",
    "hi5",
    "taringa",
  ],
  personalCorrespondence: [
    "family",
    "personal",
    "friend",
    "hello",
    "regards",
    "love",
    "catch-up",
    "private",
    "greeting",
    "how are you",
    "thinking of you",
    "celebration",
    "holiday",
    "birthday",
    "wedding",
    "anniversary",
    "photos",
    "letter",
    "update from me",
    "stay in touch",
  ],
  remindersAndNotifications: [
    "reminder",
    "alert",
    "calendar",
    "schedule",
    "notify",
    "don't forget",
    "upcoming",
    "event",
    "appointment",
    "meeting",
    "reservation",
    "due date",
    "remind",
    "it's time",
    "you have",
    "task",
    "alert",
    "follow-up",
    "save the date",
    "notification",
  ],
  spamOrJunk: [
    "spam",
    "unsubscribe",
    "junk",
    "ad",
    "promotion",
    "irrelevant",
    "low priority",
    "marketing",
    "campaign",
    "advertisement",
    "buy now",
    "cheap",
    "click here",
    "limited time",
    "win",
    "guaranteed",
    "congratulations",
    "exclusive offer",
    "fast",
    "low cost",
    "lottery",
  ],
  travelAndReservations: [
    "flight",
    "booking",
    "reservation",
    "travel",
    "ticket",
    "hotel",
    "check-in",
    "itinerary",
    "departure",
    "arrival",
    "trip",
    "journey",
    "vacation",
    "holiday",
    "rental",
    "schedule",
    "passenger",
    "boarding",
    "confirmation",
    "plan",
  ],
  miscellaneousOrOthers: [
    "miscellaneous",
    "general",
    "other",
    "varied",
    "assorted",
    "uncategorized",
    "not specific",
    "various",
    "diverse",
    "random",
    "unsorted",
    "misc",
    "mixed",
    "different",
    "unknown",
    "unclear",
    "catch-all",
    "broad",
    "indeterminate",
    "non-specific",
    "generic",
  ],
  alerts: [
    "alert",
    "notification",
    "warning",
    "emergency",
    "critical",
    "danger",
    "urgent",
    "immediate attention",
    "attention required",
    "action required",
    "notify",
    "reminder",
    "escalate",
    "urgent action",
    "high alert",
    "emergency response",
    "alert message",
    "imminent danger",
    "security alert",
    "system failure",
    "safety warning",
    "urgent notice",
    "warning message",
    "situation update",
    "fire alert",
    "health warning",
    "alert notification",
    "notification required",
    "notification sent",
    "issue detected",
    "critical warning",
    "dangerous condition",
    "immediate response",
    "take action",
    "attention needed",
    "immediate update",
    "emergency notification",
    "pending alert",
    "escalation required",
    "action needed",
    "safety notification",
    "warning alert",
    "immediate risk",
    "emergency contact",
    "attention necessary",
    "urgent warning",
    "crisis alert",
    "watch out",
    "alert triggered",
    "immediate action required",
    "high priority alert",
    "alert received",
    "incident alert",
    "caution",
    "warning issued",
    "situation requires attention",
    "security breach",
    "threat detected",
    "disaster alert",
    "alert activation",
    "imminent threat",
    "disruption alert",
    "risk alert",
    "safety concern",
    "emergency action",
    "alert warning",
    "condition alert",
  ],
};

export const newsletterIndicators = [
  "unsubscribe",
  "subscribe",
  "newsletter",
  "update preferences",
  "weekly digest",
  "monthly roundup",
  "top stories",
  "highlights",
  "recap",
  "exclusive offer",
  "insider tips",
  "what’s new",
  "promotions",
  "featured",
  "in case you missed it",
  "latest updates",
  "for you",
  "stay informed",
  "trends",
  "recommendations",
  "deals",
  "your weekly",
  "get started",
  "our picks",
  "best of the week",
  "don’t miss",
  "news you can use",
  "roundup",
  "from our team",
  "offers inside",
  "curated for you",
  "handpicked",
  "essential reads",
  "tips and tricks",
  "resources",
  "spotlight",
  "insights",
  "get the latest",
  "subscriber exclusive",
  "thank you for subscribing",
  "free updates",
  "your guide",
  "learn more",
  "discover",
  "explore",
  "your account",
  "preferred subscriber",
  "member benefits",
  "pro tips",
];
